import {Person} from '../models';

export const People: Person[] = [
  {
      "id": 1,
      "nombre": "roberth",
      "apellido": "zambrano",
      "identificacion": "2222222222",
      "sueldo": "500",
      "prestamo": "100",
      "horaExtra": "5"
  },
  {
      "id": 3,
      "nombre": "jose",
      "apellido": "Pepe",
      "identificacion": "2222222222",
      "sueldo": "4000",
      "prestamo": "200",
      "horaExtra": "5"
  },
  {
      "id": 4,
      "nombre": "pipo",
      "apellido": "perra",
      "identificacion": "1111111111",
      "sueldo": "500",
      "prestamo": "0",
      "horaExtra": "4"
  },
  {
      "id": 6,
      "nombre": "andres",
      "apellido": "federico",
      "identificacion": "1234567896",
      "sueldo": "4000",
      "prestamo": "200",
      "horaExtra": "5"
  }
]